name: 'Git Tag Generator'
description: 'Generate and push SemVer formatted git tag on push/merge'
author: 'Michal Zegar'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  new_tag:
    description: 'Generated tag'
branding:
  icon: 'tag'  
  color: 'blue'